# Generated by Django 3.0.6 on 2020-08-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200809_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='category_name',
        ),
    ]
