# Generated by Django 3.0.6 on 2020-08-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
    ]
