# Generated by Django 3.0.6 on 2020-08-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_pic',
            field=models.ImageField(null=True, upload_to='images//'),
        ),
    ]
