# Generated by Django 3.0.6 on 2020-09-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blog_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='email',
        ),
    ]
