# Generated by Django 3.0.6 on 2020-09-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200903_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='newsletteruser',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
